#!/usr/bin/env python
"""
Takes every second sequence from a fasta file (0,2,4,...)

Usage:
  everySecond [options] <infile>
  everySecond -h | --help

Options:
  -v --verbose             Print progress to STDERR.
  -h --help                Show this screen.

"""

import sys
from itertools import islice

from docopt import docopt

from Bio.Seq import Seq
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.SeqIO.FastaIO import FastaWriter
from Bio.Alphabet import IUPAC


if __name__ == "__main__":
    args = docopt(__doc__)
    filename = args["<infile>"]
    is_verbose = args["--verbose"]

    outfile = "{}.seconds.fasta".format(filename)

    records = SeqIO.parse(filename,'fasta')
    writer = FastaWriter(outfile, wrap=None)
    writer.write_header()

    for rec in islice(records, 0, None, 2):
        rec.seq = rec.seq.ungap("-")
        writer.write_record(rec)
    if is_verbose:
        sys.stderr.write('Every second sequence written to {}\n'.format(outfile))
