#!/usr/bin/python
import sys
from Bio.Seq import Seq
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import string
from Bio.SeqIO.FastaIO import FastaWriter

from Bio.Alphabet import IUPAC

if len(sys.argv)!=2:
    print 'Usage: everySecond <filename>\nTakes every second sequence from a fasta file (1,3,5,...)'
    sys.exit()

filename = str(sys.argv[1])

records = SeqIO.parse(open(filename),'fasta')

writer = FastaWriter(open(filename+".seconds.fasta","w"), wrap=None)
writer.write_header()

counter = 0
for rec in records:
    if counter%2 == 0:
        #print rec.name
        rec.seq = rec.seq.ungap("-")
        writer.write_record(rec)
    counter = counter + 1
print 'Seconds written to ' + filename+".seconds.fasta"
