#!/usr/bin/env python
"""
Takes every second sequence from a fasta file (1,3,5,...)

Usage:
  everySecond [options] <infile>
  everySecond -h | --help

Options:
  -v --verbose             Print progress to STDERR.
  -h --help                Show this screen.

"""

import sys

from docopt import docopt

from Bio.Seq import Seq
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.SeqIO.FastaIO import FastaWriter
from Bio.Alphabet import IUPAC


if __name__ == "__main__":
    args = docopt(__doc__)
    filename = args["<infile>"]
    is_verbose = args["--verbose"]

    outfile = "{}.seconds.fasta".format(infile)

    records = SeqIO.parse(filename,'fasta')
    writer = FastaWriter(outfile, wrap=None)
    writer.write_header()

    for rec in records[::2]:
        rec.seq = rec.seq.ungap("-")
        writer.write_record(rec)
    if is_verbose:
        sys.stderr.write('Every second sequence written to {}\n'.format(outfile))
